config/routes.rb
AkitaThermostat::Application.routes.draw do

  resources :observacions

  resources :pais

  resources :issues

  resources :alarms

  resources :locations

  resources :history_thermostats

  resources :planners
  get '/observacions/likes' => 'observacions#likes'
  get '/observacions/dislikes' => 'observacions#dislikes'
  get '/thermostats/new' => 'thermostats#new', as: 'new_thermostat'

  get '/planners/new/:id' => 'planners#new', as: 'new'
  get '/planners/history/:id' => 'planners#history', as: 'planner_history'
  get '/thermostats/devise' => 'thermostats#devise', as: 'devise'
  
  get '/issues/resolution/:id' => 'issues#resolution'
  get '/issues/new/:id' => 'issues#new'
  get '/issues/history/:id' => 'issues#history'
  get '/issues/change_status/:id' => 'issues#change_status', :as => 'change_status_issue'
  get '/issues/open/:id' => 'issues#open', :as => 'open_issue'

  get '/history_thermostats/:id' => 'history_thermostats#index'

  get '/alarms/new/:id' => 'alarms#new'
  

  get 'users/change_role/:id' => 'users#change_role', :as => 'change_role_user'
  get 'users/change_enable/:id' => 'users#change_enable', :as => 'change_enable_user'
  get 'users/delete/:id' => 'users#destroy', :as => 'delete_user'
  
 
  get "registrations/edit"
  get "/error" => "static_pages#error"
resources :locations do
   get 'register', on: :collection
 end
  devise_for :users
  resources :users
  resources :thermostats

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :thermostat

  validates :description, presence: {:message => "Es un campo obligatorio"}

  def change_status
   self.status = 'CANCELADO'
   self.description = "Problema cancelado"
   self.save!
end

def open
	self.status = 'ABIERTO'
	self.save!
end

end

app/controllers/issues_controller.rb
#Este es el controlador de problemas, se administra los problemas desde u reporte
#y su respectiva status apartir de su reporte.
class IssuesController < ApplicationController

  before_action :set_issue, only: [:change_status, :open,  :show, :edit, :update, :destroy]
  #respond_to :js, only: :change_status

  # GET /issues
  # GET /issues.json
  def index
    if (current_user!=nil)
      @issues = Issue.all
    else
      redirect_to root_path
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  def change_status
    @issue.change_status
    respond_to do |format|
      format.html { redirect_to "/issues/history/" + @issue.thermostat_id.to_s }
      format.json { head :no_content }
    end
  end

  def open
    @issue.open
      respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end


  def history
    @thermostat = Thermostat.find(params[:id])
    @issues = @thermostat.issues
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @thermostat = Thermostat.find(params[:id])
    @issue.thermostat = @thermostat
  end

  # GET /issues/1/edit
  def edit

  end

  def resolution
    @issue = Issue.find(params[:id])
    @issue.status = 'RESUELTO'
    @issue.save

  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.status = 'ABIERTO'
    @issue.resolution = ''
    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Problema registrado exitosamente' }
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Problema editado exitosamente' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:thermostat_id, :description, :status, :resolution)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_validated_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
    <%= f.hidden_field :thermostat_id%>
  <div class="field">
    <%= f.label :description, 'Descripcion del problema' %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="actions">
    <%= f.submit "Registrar problema", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editar problema</h1>

<%= form_validated_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description, 'Descripcion del problema' %><br>
    <%= f.text_area :description, :value => @issue.description %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Editar', :class => 'btn btn-info' %>
  </div>
<% end %>

<%= link_to 'Volver', "/issues/history/"+ @issue.thermostat.id.to_s, :class => 'btn btn-default' %>

app/views/issues/history.html.erb
<h1>Lista de problemas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Termostato</center></th>
      <th><center>Descripcion del problema</center></th>
      <th><center>Estado</center></th>
      <th><center>Resolucion</center></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><center><%= issue.thermostat.serial %></center></td>
        <td><center><%= issue.description %></center></td>
        <td id="status <%=issue.id%>"><center><%= issue.status %></center></td>
        <td><center><%= issue.resolution %></center></td>
        <td><%= link_to 'Ver', issue, :class => 'btn btn-mini btn-default' %></td>
        <%if issue.status != 'RESUELTO' && issue.status != 'CANCELADO' %>
        <td class="cancel_button" id="<%=issue.id%>"><%= link_to 'Cancelar', change_status_issue_path(issue), :class => 'btn btn-mini btn-primary'%></td>
        <td><%= link_to 'Editar', edit_issue_path(issue), :class => 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Eliminar', issue, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-mini btn-danger'   %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Volver', thermostats_path, class: "btn btn-default" %>

app/views/issues/index.html.erb
<h1>Lista de problemas</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Termostato</center></th>
      <th><center>Descripcion del problema</center></th>
      <th><center>Estado</center></th>
      <th><center>Resolucion</center></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <%if issue.status != 'CANCELADO'  %>
        <td><center><%= issue.thermostat.serial %></center></td>
        <td><center><%= issue.description %></center></td>
        <td><center><%= issue.status %></center></td>
        <td><center><%= issue.resolution %></center></td>
        <%if issue.status != 'RESUELTO'  %>
        <td><%= link_to 'Resolver', {:controller => :issues, :action => "resolution", :id => issue.id}, :class => 'btn btn-mini btn-info'  %></td>
        <%end%>
        <%if issue.status == 'RESUELTO'  %>
        <td><%= link_to 'Abrir', open_issue_path(issue), :class => 'btn btn-mini btn-warning'%></td>
        <%end%>
        <td><%= link_to 'Eliminar', issue, method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-mini btn-danger'   %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Volver', users_path, class: "btn btn-default" %>

app/views/issues/new.html.erb
<h1>Registrar problema</h1>

<%= render 'form' %>

<%= link_to 'Volver', thermostats_path, class: "btn btn-default" %>

app/views/issues/resolution.html.erb
<h1>Resolver problema</h1>

<%= form_validated_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description, 'Descripcion del problema' %><br>
    <%= f.text_area :description, :value => @issue.description %>
  </div>
  
    <div class="field">
    <%= f.label :resolution, 'Solucion' %><br>
    <%= f.text_area :resolution %>
  </div>
  
  
  <div class="actions">
    <%= f.submit 'Guardar', :class => "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Volver', issues_path, :class => "btn btn-default" %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Termostato:</strong>
  <%= @issue.thermostat.serial %>

</p>

<p>
  <strong>Descripcion del problema:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Resolucion:</strong>
  <%= @issue.resolution %>
</p>

<%= link_to 'Editar', edit_issue_path(@issue), :class => 'btn btn-info'%> |
<%= link_to 'Volver', "/issues/history/"+ @issue.thermostat.id.to_s, :class => 'btn btn-default' %>