config/routes.rb
AkitaThermostat::Application.routes.draw do

  resources :observacions

  resources :pais

  resources :issues

  resources :alarms

  resources :locations

  resources :history_thermostats

  resources :planners
  get '/observacions/likes' => 'observacions#likes'
  get '/observacions/dislikes' => 'observacions#dislikes'
  get '/thermostats/new' => 'thermostats#new', as: 'new_thermostat'

  get '/planners/new/:id' => 'planners#new', as: 'new'
  get '/planners/history/:id' => 'planners#history', as: 'planner_history'
  get '/thermostats/devise' => 'thermostats#devise', as: 'devise'
  
  get '/issues/resolution/:id' => 'issues#resolution'
  get '/issues/new/:id' => 'issues#new'
  get '/issues/history/:id' => 'issues#history'
  get '/issues/change_status/:id' => 'issues#change_status', :as => 'change_status_issue'
  get '/issues/open/:id' => 'issues#open', :as => 'open_issue'

  get '/history_thermostats/:id' => 'history_thermostats#index'

  get '/alarms/new/:id' => 'alarms#new'
  

  get 'users/change_role/:id' => 'users#change_role', :as => 'change_role_user'
  get 'users/change_enable/:id' => 'users#change_enable', :as => 'change_enable_user'
  get 'users/delete/:id' => 'users#destroy', :as => 'delete_user'
  
 
  get "registrations/edit"
  get "/error" => "static_pages#error"
resources :locations do
   get 'register', on: :collection
 end
  devise_for :users
  resources :users
  resources :thermostats

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :thermostats 
  has_many :locations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: {:message => "Es un campo obligatorio"}

  #validate :password_complexity

  #def password_complexity
  #  if password.present? and not password.match(/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]). /)
  #    errors.add :password, "debe tener al menos 8 caracteres, una minuscula, una mayuscula, y un numero"
  #  end
  #end

  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
   end

   def change_role
     if self.role == 1
        self.role = 2
      else
        self.role = 1
     end
     self.save!
   end

   def change_enable
    if self.enable == true
      self.enable = false
    else
      self.enable = true
    end
     self.save!
   end

   after_create do
    self.role = 2 
    self.enable = true
    self.save!
   end

end

app/controllers/users_controller.rb
#este controlador administra los usuarios con la ayuda de la gema devise.
class UsersController < ApplicationController
	load_and_authorize_resource
before_action :set_user, only: [:change_role,:change_enable, :destroy, :show, :edit]
  # GET /user_managers
  # GET /user_managers.json
  def index
    @users = User.all
  end

  # POST /user_managers
  # POST /user_managers.json

  def show
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:username,:email, :password, :password_confirmation))
      @user.save
      flash[:success] = "Usuario Actualizado"
      redirect_to :controller => :users, :action => "index"      
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def change_role
    @user.change_role
      respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def change_enable
    @user.change_enable
      respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username,:email, :password, :password_confirmation)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Editar Usuario</h1>
<h1> PAISES </h1>
<div class="col-xs-3">
<%= form_for @user do |f| %>

  <p><%= f.label :username, "Nombre de Usuario" %><br />
  <%= f.text_field :username %></p>

  <div><%= f.label :email, "Correo" %><br />
  <%= f.email_field :email, autofocus: true %></div>
      
  <p><%= f.label :password, 'Nueva Contraseña'%>
  <%= f.password_field :password, :class => 'form-control' %>

  <p><%= f.label :password_confirmation, 'Confirme Contraseña' %>
  <%= f.password_field :password_confirmation, :class => 'form-control' %>

  <p><%= f.submit (@user.new_record? ? 'Crear' : 'Guardar cambios'), :class => 'btn btn-lg btn-info' %></p>

<% end %>
</div>
<p>Administrar paises</p>
<%= link_to 'Atrás', users_path, class: "btn btn-default" %>

app/views/users/index.html.erb
<h1>Lista de usuarios</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Nombre</center></th>
      <th><center>Cuenta</center></th>
      <th><center>Fecha de Creacion</center></th>
      <th><center>Rol</center></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><center><%= user.username%></center></td>
        <td><center><%= user.email%></center></td>
        <td><center><%= user.created_at.strftime("%d/%m/%Y")%></center></td>
        <%if user.role == 1 %>
          <td><center>Administrador</center></td>
        <%else%>
          <td><center>Usuario</center></td>
        <%end%>
        <td><%= link_to 'Cambiar Rol', change_role_user_path(user), :class => 'btn btn-mini'   %></td>
        <%if user.enable == true%>
        <td><%= link_to 'Bloquear', change_enable_user_path(user), :class => 'btn btn-mini btn-warning'   %></td>
        <%else%>
        <td><%= link_to 'Desbloquear', change_enable_user_path(user), :class => 'btn btn-mini'   %></td>
        <%end%>
        <td><%= link_to 'Editar', edit_user_path(user), :class => 'btn btn-mini btn-info'  %></td>
        <td><%= link_to 'Eliminar', user_path(user), method: :delete, data: { confirm: 'Seguro?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>