config/routes.rb
AkitaThermostat::Application.routes.draw do

  resources :observacions

  resources :pais

  resources :issues

  resources :alarms

  resources :locations

  resources :history_thermostats

  resources :planners
  get '/observacions/likes' => 'observacions#likes'
  get '/observacions/dislikes' => 'observacions#dislikes'
  get '/thermostats/new' => 'thermostats#new', as: 'new_thermostat'

  get '/planners/new/:id' => 'planners#new', as: 'new'
  get '/planners/history/:id' => 'planners#history', as: 'planner_history'
  get '/thermostats/devise' => 'thermostats#devise', as: 'devise'
  
  get '/issues/resolution/:id' => 'issues#resolution'
  get '/issues/new/:id' => 'issues#new'
  get '/issues/history/:id' => 'issues#history'
  get '/issues/change_status/:id' => 'issues#change_status', :as => 'change_status_issue'
  get '/issues/open/:id' => 'issues#open', :as => 'open_issue'

  get '/history_thermostats/:id' => 'history_thermostats#index'

  get '/alarms/new/:id' => 'alarms#new'
  

  get 'users/change_role/:id' => 'users#change_role', :as => 'change_role_user'
  get 'users/change_enable/:id' => 'users#change_enable', :as => 'change_enable_user'
  get 'users/delete/:id' => 'users#destroy', :as => 'delete_user'
  
 
  get "registrations/edit"
  get "/error" => "static_pages#error"
resources :locations do
   get 'register', on: :collection
 end
  devise_for :users
  resources :users
  resources :thermostats

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/planner.rb
class Planner < ActiveRecord::Base
  belongs_to :thermostat

  validates :week_day, :temperature, :schedule, presence: {:message => "Es un campo obligatorio"}

  validates :temperature, numericality: {:message => "La temperatura solo permite enteros"}
  validates :temperature, numericality: {greater_than: -20, less_than: 60, :message => "La temperatura maxima debe ser mayor a -20 y menor a 60" }
end

app/controllers/planners_controller.rb
#Este controlador se usar para la planificacion de temperaturas por dia en el thermostato

class PlannersController < ApplicationController
  before_action :set_planner, only: [:show, :edit, :update, :destroy]

  # GET /planners
  # GET /planners.json
  def index
   @planners = Planner.all
   
  end

  # GET /planners/1
  # GET /planners/1.json
  def show
  end

  # GET /planners/new
  def new
    @planner = Planner.new
    @thermostat = Thermostat.find(params[:id])
    @planner.thermostat = @thermostat
    @planner.default = 20
    
  end
  # GET /planners/1/edit
  def edit
  end

  def history
    @thermostat = Thermostat.find(params[:id])
    @planners = @thermostat.planners
  end

  # POST /planners
  # POST /planners.json
  def create
    @planner = Planner.new(planner_params)

    respond_to do |format|
      if @planner.save
        format.html { redirect_to @planner, notice: 'Cronograma creado exitosamente.' }
        format.json { render action: 'show', status: :created, location: @planner }
      else
        format.html { render action: 'new' }
        format.json { render json: @planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planners/1
  # PATCH/PUT /planners/1.json
  def update
    respond_to do |format|
      if @planner.update(planner_params)
        format.html { redirect_to @planner, notice: 'Planner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planners/1
  # DELETE /planners/1.json
  def destroy
    @planner.destroy
    respond_to do |format|
      format.html { redirect_to planners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planner
      @planner = Planner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planner_params
      params.require(:planner).permit(:week_day, :temperature, :default, :schedule, :thermostat_id)
    end
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/views/planners/_form.html.erb
<%=form_validated_for(@planner) do |f| %>
  <% if @planner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planner.errors.count, "error") %> prohibited this planner from being saved:</h2>

      <ul>
      <% @planner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :week_day, "Dia de la semana" %><br>
    <%= f.select :week_day, options_for_select([["Lunes"], ["Martes"], ["Miercoles"], ["Jueves"], ["Viernes"], ["Sabado"], ["Domingo"]]) %>
  </div>
  
  <div class="field">
    <%= f.label :temperature, "Temperatura" %><br>
    <%= f.number_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :schedule, "Franja horaria" %><br>
    <%= f.select :schedule, options_for_select([["Madrugada"], ["Mañana"], ["Tarde"], ["Noche"]]) %>
  </div>
  <%= f.hidden_field :thermostat_id%>

  <div class="actions">
    <p><%= f.submit (@planner.new_record? ? 'Registrar' : 'Editar'), :class => 'btn btn-lg btn-primary' %></p>
  </div>
<% end %>

app/views/planners/edit.html.erb
<h1>Editar planificacion</h1>

<%= render 'form' %>

<td><%= link_to 'Volver', planner_history_path, class: "btn btn-default" %></td>

app/views/planners/history.html.erb
<h1>Lista de planificaciones</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Dia de la Semana</th>
      <th>Temperatura</th>
      <th>Franja Horaria</th>
      <th>Serial del termostato</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @planners.each do |planner| %>
      <tr>
        <td><%= planner.week_day %></td>
        <td><%= planner.temperature %></td>
        <td><%= planner.schedule %></td>
        <td><%= planner.thermostat.serial %></td>
        <td><%= link_to 'Ver', planner, :class => 'btn btn-mini btn-default' %></td>
        <td><%= link_to 'Editar', edit_planner_path(planner), :class => 'btn btn-mini btn-info' %></td>
         <td><%= link_to 'Eliminar', planner_path(planner), method: :delete, data: { confirm: 'Seguro?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>  
    <% end %>
  </tbody>
</table>

<br>

app/views/planners/index.html.erb
<h1>Lista de planificaciones</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Dia de la Semana</th>
      <th>Temperatura</th>
      <th>Franja Horaria</th>
      <th>ID del termostato</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @planners.each do |planner| %>
      <tr>
        <td><%= planner.week_day %></td>
        <td><%= planner.temperature %></td>
        <td><%= planner.schedule %></td>
        <td><%= planner.thermostat_id %></td>
        <td><%= link_to 'Mostrar', planner, :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Editar', edit_planner_path(planner), :class => 'btn btn-mini' %></td>
         <td><%= link_to 'Eliminar', planner_path(planner), method: :delete, data: { confirm: 'Seguro?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><%= link_to 'Registrar Planificacion', :controller => :planners, :action => "new", :id => thermostat
_id %></td>

app/views/planners/new.html.erb
<h1>Nueva planificacion</h1>

<%= render 'form' %>

<td><%= link_to 'Volver', planner_history_path, class: "btn btn-default" %></td>

app/views/planners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dia de la semana:</strong>
  <%= @planner.week_day %>
</p>

<p>
  <strong>Temperatura:</strong>
  <%= @planner.temperature %>
</p>

<p>
  <strong>Franja:</strong>
  <%= @planner.schedule %>
</p>


<%= link_to 'Editar', edit_planner_path(@planner), :class => 'btn btn-info' %>|
<%= link_to 'Atrás', thermostats_path,:class => 'btn btn-default' %>