config/routes.rb
AkitaThermostat::Application.routes.draw do

  resources :observacions

  resources :pais

  resources :issues

  resources :alarms

  resources :locations

  resources :history_thermostats

  resources :planners
  get '/observacions/likes' => 'observacions#likes'
  get '/observacions/dislikes' => 'observacions#dislikes'
  get '/thermostats/new' => 'thermostats#new', as: 'new_thermostat'

  get '/planners/new/:id' => 'planners#new', as: 'new'
  get '/planners/history/:id' => 'planners#history', as: 'planner_history'
  get '/thermostats/devise' => 'thermostats#devise', as: 'devise'
  
  get '/issues/resolution/:id' => 'issues#resolution'
  get '/issues/new/:id' => 'issues#new'
  get '/issues/history/:id' => 'issues#history'
  get '/issues/change_status/:id' => 'issues#change_status', :as => 'change_status_issue'
  get '/issues/open/:id' => 'issues#open', :as => 'open_issue'

  get '/history_thermostats/:id' => 'history_thermostats#index'

  get '/alarms/new/:id' => 'alarms#new'
  

  get 'users/change_role/:id' => 'users#change_role', :as => 'change_role_user'
  get 'users/change_enable/:id' => 'users#change_enable', :as => 'change_enable_user'
  get 'users/delete/:id' => 'users#destroy', :as => 'delete_user'
  
 
  get "registrations/edit"
  get "/error" => "static_pages#error"
resources :locations do
   get 'register', on: :collection
 end
  devise_for :users
  resources :users
  resources :thermostats

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :thermostats
  belongs_to :user
  has_one :alarm

  validates :name, :city, :address, :presence => true

  validates :name, :city, :address, presence:{:message => "Es un campo obligatorio"}
  validates :name, length: {minimum: 4, maximum: 20, :message => "La propiedad debe tener minimo 4 y maximo 20 caracteres"}
  validates :city, length: {minimum: 4, maximum: 20, :message => "La ciudad debe tener minimo 4 y maximo 20 caracteres"}
  validates :address, length: {minimum: 4, maximum: 20, :message => "La direccion debe tener minimo 4 y maximo 20 caracteres"}



end

app/controllers/locations_controller.rb
#Ese controladora maneja la ubicaciones de las casas de los usuarios
#aqui se puede administrar una ubicacion.
class LocationsController < ApplicationController

  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
     #@locations = Location.all
    if (current_user!=nil)
      @locations = current_user.locations
    else
      redirect_to root_path
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    if @location.user_id != current_user.id
      redirect_to '/'
    end
  end

  # GET /locations/new
  def new
    @location = Location.new
     #@thermostat = Thermostat.find(params[:id])
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    @location.user=current_user
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Ubicacon registrada exitosamente' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Ubicacion editada exitosamente' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:name, :city, :address, :user_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_validated_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :name, 'Nombre' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city, 'Ciudad' %><br>
    <%= f.select :city, ['Cochabamba', 'La Paz', 'Santa Cruz'] %>

  </div>
  <div class="field">
    <%= f.label :address, 'Direccion' %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit (@location.new_record? ? 'Registrar' : 'Editar'), :class => 'btn btn-primary btn-sm' %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editar Ubicacion</h1>

<%= render 'form' %>

<%= link_to 'Atras', locations_path, class: "btn btn-default btn-sm" %>

app/views/locations/index.html.erb
<h1>Lista de ubicaciones</h1>

<div align="right">
<%= link_to 'Nueva Ubicacion', new_location_path, :class => 'btn btn-default btn-lg active' %>
</div>
<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Nombre</center></th>
      <th><center>Ciudad</center></th>
      <th><center>Direccion</center></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><center><%= location.name %></center></td>
        <td><center><%= location.city %></center></td>
        <td><center><%= location.address %></center></td>
        <td><%= link_to 'Ver', location, :class => 'btn btn-mini btn-default' %></td>
        <td><%= link_to 'Editar', edit_location_path(location), :class => 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Eliminar', location, method: :delete, data: { confirm: 'Esta seguro?' }, :class => 'btn btn-mini btn-danger' %></td>
        <%if location.alarm == nil%>
        <td><%= link_to 'Registrar alarma',"/alarms/new/"+location.id.to_s, :class => 'btn btn-mini btn-warning' %></td> 
        <%else%>
        <td><%= link_to 'Ver alarma', location.alarm, :class => 'btn btn-mini btn-warning' %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<h1>Nueva Ubicacion</h1>

<%= render 'form' %>

<%= link_to 'Atras', locations_path, class: "btn btn-default" %>

app/views/locations/new_thermostat.html.erb
<%= form_for @location, :url =>(add_thermostat_path(@location.id.to_s)), :method => 'post' do |f| %>
<%= select_tag :thermostat,options_from_collection_for_select(Thermostat.all,'id','serial')  %>
<%=f.submit 'Agregar'%>
<%end%>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>
<H1><%= @location.name %></H1>

<p>
  <strong>Ciudad:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @location.address %>
</p>


<h1><center>Lista de termostatos</center></h1>

<div align="right">
<%= link_to 'Agregar Termostato', new_thermostat_path, :class => 'btn btn-default btn-lg active' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><center>Serial</center></th>
      <th><center>Temperatura</center></th>
      <th><center>Humedad</center></th>
      <th><center>Energia</center></th>
    </tr>
  </thead>

  <tbody>
    <% @location.thermostats.each do |thermostat| %>
      <tr>
        <td><center><%= thermostat.serial %></center></td>
        <td><center><%= thermostat.temperature %></center></td>
        <td><center><%= thermostat.humidity %></center></td>
        <td><center><%= thermostat.energy %></center></td>
        <td><%= link_to 'Ver', thermostat , :class => 'btn btn-mini btn-default'%></td>
        <td><%= link_to 'Editar', edit_thermostat_path(thermostat),  :class => 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Eliminar', thermostat, method: :delete, data: { confirm: 'Está seguro?' }, :class => 'btn btn-mini btn-danger'%></td>
        <td><%= link_to 'Registrar Planificacion', {:controller => :planners, :action => "new", :id => thermostat.id}, :class =>'btn btn-default btn-lg'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Editar', edit_location_path(@location), :class => 'btn btn-info' %> |
<%= link_to 'Atrás', locations_path, :class => 'btn btn-default' %>